# Generated by Django 4.0.3 on 2022-03-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0002_auto_20200121_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_month',
            field=models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'March'), ('4', 'Apr'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=200),
        ),
    ]
